### PR TITLE
Use an isolated tmpdir

### PR DESCRIPTION
**Pull request by bersace**
Closes: #367 

@dtseiler Can you test this ?

### CODE REVIEW

**Comment by dtseiler** [comment]
Yep I'll patch a local copy and test.

**Comment by dtseiler** [comment]
Confirmed it created two distinct pgbadger-XXXX format named directories under TMPDIR. I was able to run two instances of pgbadger without a problem!

**Comment by bersace** [comment]
cc @darold

**Comment by bersace** [comment]
There is a problem with this change : It invalidate the default behaviour of pgBadger which is to avoid concurrent run on same report. It's up to the user to assign a pid-dir different to manage to instances of pgBadger.

I'm considering reverting this change.

**Pull request merged**
